#include <iostream>
#include <fstream>
#include "CodeGenerator.h"

using namespace std;

CodeGen::CodeGen (string filename, LexicalAnalyzer * L)
{
    lex = L;
    string cppname = filename.substr (0, filename.length()-3) + ".cpp";
    cpp.open (cppname.c_str());
    cpp << "// Autogenerated Scheme to C++ Code\n"
        << "// File: " << cppname << "\n"
        << "#include <iostream>\n"
        << "#include \"Object.h\"\n"
        << "using namespace std;\n\n";
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
CodeGen::~CodeGen ()
{
    cpp << "int main()\n"
        << "{\n"
        << "\tObject result = main();\n"
        << "\tstringstream s;\n"
        << "\ts << result;\n"
        << "\tint status;\n"
        << "\ts >> status;\n"
        << "\treturn status;\n"
        << "}\n";
    cpp.close();
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
void CodeGen::WriteCode (int tabs, string code)
{
    for (int t = 0; t < tabs; t++)
        cpp << '\t';
    cpp << code;
}
