#! /usr/bin/env atf-sh

TESTS_DIR=$(atf_get_srcdir)

tests=""

for path in ${TESTS_DIR}/*.ss
do
    file=${path##${TESTS_DIR}/}

    case ${file} in
        *.bad.ss)
            name=${file%%.bad.ss}_bad
            action="not-match"
            ;;
        *.ss)
            name=${file%%.ss}
            action="match"
            ;;
    esac

    atf_test_case ${name}
    eval "${name}_head() {
        atf_set descr ${file}
        atf_set require.files ${path}
        atf_set require.progs P3.out
    }
    ${name}_body() {
        atf_check -o ${action}:'^0 errors' P3.out ${path}
    }"

    tests="${tests} ${name}"
done

atf_init_test_cases() {
    for t in ${tests}
    do
        atf_add_test_case ${t}
    done
}

# Local Variables:
# mode: sh
# End:
# vim: filetype=sh fileformat=unix
